M48
; DRILL file KiCad 10.0.5 date 2026-10-01T19:38:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-01T19:38:53+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X14.46Y-7.0
X19.54Y-5.984
X19.54Y-8.016
T2
X3.0Y-34.0
X15.0Y-2.0
X81.0Y-2.0
X93.0Y-34.0
M30
